import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainLayout from './MainLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <MainLayout>{children}</MainLayout>
        </body>
      </html>
  )
}


// json-server --watch db.json --port 8000


    // const handleUpdateCart = (item, e) => {
        // const newQuantity = e.target.value;
        // // Update the quantity of the item in the cartItem array
        // const updatedCartItem = cartItem.map((item) => {
        //     if (item.id === item.id) {
        //         return { ...item, quantity: newQuantity };
        //     }
        //     return item;
        // });
        // Update the cartItem state with the updatedCartItem array
        // setCartItem(updatedCartItem);
    // }}